# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[1.6,)" # Require at least 1.6.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="lotl"
version="${file.jarVersion}"
displayName="LeyOfTheLand"
credits="The Wack Pack"
authors="Nick 'Arkinion' Rose, Jacob 'Epicjii' Liggett, And Tom 'Pearhair' Yarrow"
description='''
A magic mod that is actually a tech mod.
'''
[[dependencies.lotl]]
    modId="forge"
    mandatory=true
    versionRange="[31.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lotl]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
